### ISSUE TITLE
CSP can break fallback for `waitAsync`

### ISSUE THREAD

**Issue by logotip4ik** [WebReflection/sabayon#6]
First of all, big thank you for your work! Your software is always top notch. Many kudos to you ❤️

I think in v1 coincident was also prone to such issue unfortunately. The main thing is that I don't want to add `data:` to my `content-security-policy`, but without this, Firefox users will be unable to use website, because it sill doesn't support `Atomics.waitAsync()` and fallback worker:

https://github.com/WebReflection/sabayon/blob/9f3293e1ec14932738fc61f4c65ddcf7b263dc23/src/shared.js#L85

also wont be loaded, because `content-security-policy` will disallow to run javascript from `data:`.

So, the reproduction can be as such:

1. add `content-security-policy: default-src 'self'` to response headers of the size;
2. try to make use of function in worker in Firefox;

I thought about how to resolve this and the only thing that came to my mind is to add escape hatch for users via self hosted worker. So fallback will try to load `/__sabayon_async_fallback.js` (for example) instead of inline `data:...`. This will be allowed by csp, because it is `self` resource.

**Comment by WebReflection** [comment]
> Firefox users will be unable to use website, because it sill doesn't support `Atomics.waitAsync()`

this is a **Firefox** issue to me though ... I can't make this portable or more cumbersome for Firefox sake but I like your idea:

> add escape hatch for users via self hosted worker

the gotcha is that it *MUST* do exactly what my data does:

```js
onmessage=e=>postMessage(!Atomics.wait(...e.data))
```

the last gotcha is how am I supposed to pass that fallback URL to a generic patch, because IIRC *CSP* doesn't throw in JS, it throws in the browser, and on top of that, `/__sabayon_async_fallback.js` might be too broad of a scope + people don't usually like js files at the root of their sites ... **but**, if you have any idea how to feature-detect the fact Firefox will throw ('cause maybe it does already, I haven't tested locally with CSP enabled) I might consider that and provide a best-effort fallback for `/__sabayon_wait_async.js` and let users find out the best way to provide that.

**Comment by WebReflection** [comment]
Aha ... you know what, that fallback is async anyway so actually I could simply fetch that file and provide it as fallback if found, use the `data:` thing otherwise ... this should work, but it will show weird things on the network panel ... would that work?

**Comment by WebReflection** [comment]
@logotip4ik fixed by checking *HEAD* once for the existence of `/__sabayon_wait_async.js` ... it fallsback to `data:...` if that file is nowhere reachable.

**Comment by logotip4ik** [comment]
Sorry for long delay, checked in my local repo and it works flawlessly, thanks! Glad you liked my idea. Also thanks for investigation and deep messages, it's always a pleasure to read them
